[package]
name = "ferron-http-cache"
version = "3.0.0-beta.3"
edition = "2021"

[features]
fuzz = []

[dependencies]
async-trait = "0.1"
bytes = "1"
futures-util = "0.3"
http = "1"
http-body = "1"
http-body-util = "0.1"
httpdate = "1"
quick_cache = "0.7"
ahash = "0.8"
typemap_rev = "0.4"
dashmap = "6.2.1"
cidr = "0.3"
tokio = { version = "1", features = ["sync", "time", "rt"] }
rustc-hash = "2"
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "http2", "tokio"] }
hyper-rustls = { version = "0.27", features = ["http1", "http2", "rustls-native-certs", "webpki-roots"] }
rustls = "0.23"
rustls-native-certs = "0.8"
webpki-roots = "1.0"
serde_json = "1"

ferron-core = { path = "../../core" }
ferron-http = { path = "../../types/http" }
ferron-observability = { path = "../../types/observability" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "sync", "time"] }
