[package]
name = "ferron-http-cache"
version = "3.0.0-beta.1"
edition = "2021"

[features]
fuzz = []

[dependencies]
async-trait = "0.1"
bytes = "1"
futures-util = "0.3"
http = "1"
http-body = "1"
http-body-util = "0.1"
httpdate = "1"
quick_cache = "0.6"
ahash = "0.8"
typemap_rev = "0.4"
dashmap = "6.2.1"
cidr = "0.3"

ferron-core = { path = "../../core" }
ferron-http = { path = "../../types/http" }
ferron-observability = { path = "../../types/observability" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
rustc-hash = "2"
