[package]
name = "ferron-observability-otlp"
version = "3.0.0-beta.8"
edition = "2021"

[features]
fuzz = []

[dependencies]
ferron-observability = { path = "../../types/observability" }
ferron-core = { path = "../../core" }
async-channel = "2.5.0"
tokio-util = "0.7.18"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
hyper = { version = "1", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "tokio"] }
hyper-rustls = { version = "0.27", default-features = false, features = ["http1", "http2"] }
tonic = { version = "0.14", features = ["gzip"] }
rustls = { version = "0.23", default-features = false, features = ["std", "aws_lc_rs"] }
rustls-native-certs = "0.8"
webpki-roots = "1.0"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
bytes = "1"
http = "1"
http-body-util = "0.1"
lru = "0.18.0"
prost = "0.14.4"
tonic-prost = "0.14.4"
pbjson = "0.9"
serde = "1"
serde_json = "1"
base64 = "0.23"
hex = "0.4"
rand = "0.10"
crossbeam-queue = "0.3.13"
dashmap = "6.2.1"
foldhash = "0.2.0"

[build-dependencies]
find_git = "1.2.1"
protox = "0.9.1"
tonic-prost-build = "0.14.6"
pbjson-build = "0.9"

[dev-dependencies]
hyper = { version = "1", features = ["server", "http1"] }
tokio-stream = { version = "0.1", features = ["net"] }

[package.metadata.cargo-shear]
ignored = ["pbjson", "tonic-prost"]
