[workspace]
resolver = "2"
members = [
    "bin",
    "core",
    "entrypoint",
    "modules/*",
    "types/*",
    "utils/*"
]
exclude = [
    "doctest",
    "e2e",
    "fuzz",
    # Fuzzing targets
    "modules/http-server/fuzz",
    "modules/http-ratelimit/fuzz",
    "modules/http-proxy/fuzz",
    "modules/http-cache/fuzz"
]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[patch.crates-io]
vibeio-http = { git = "https://github.com/ferronweb/vibeio-http.git", ref = "31fc488c5e05358ab6eb61ad9bfdba84ec8e4f90" } # TODO: swap to upstream vibeio-http 0.4.0 once it's released
