[package]
name = "ferron-fmt"
version = "3.0.0-beta.2"
edition = "2021"

[dependencies]
ferronconf = { version = "0.3.0", features = ["lexer-public"] }
clap = { version = "4", features = ["derive"] }

[target.'cfg(target_arch = "x86")'.dependencies]
mimalloc = { version = "0.1.50", features = ["v2"] } # Mimalloc v3 would use instructions unsupported by old 32-bit-only x86 CPUs

[target.'cfg(not(target_arch = "x86"))'.dependencies]
mimalloc = { version = "0.1.50" }

[build-dependencies]
winresource = "0.1.19"
