#!/bin/bash
if [ -d website/node_modules ]; then
  cd website
  npx lint-staged || exit $?
  cd ..
fi

for rust_file in $(git diff --name-only --cached | grep ".*\.rs$"); do
  rustfmt $rust_file || exit $?
  git add $rust_file
done

cargo clippy --fix --all-targets --allow-staged --allow-dirty || exit $?

for rust_file in $(comm -12 <(git diff --name-only --cached | sort) <(git diff --name-only | sort) | grep ".*\.rs$"); do
  git add $rust_file
done
