[package]
name = "ferron-http-map"
version = "3.0.0-beta.11"
edition = "2021"

[dependencies]
rustc-hash = "2.1"
async-trait = "0.1"
regex = "1.13.1"
http = "1"

ferron-core = { path = "../../core" }
ferron-http = { path = "../../types/http" }
ferron-observability = { path = "../../types/observability" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
bytes = "1"
http-body-util = "0.1.3"
