[package]
name = "ferron-dns-builtin"
version = "2.8.1"
edition = "2021"

[dependencies]
ferron-common = { workspace = true }
dns-update = { version = "0.5.6", optional = true, default-features = false, features = [
    "aws-lc-rs",
] }
aws-config = { version = "1.8.1", optional = true, default-features = false, features = [
    "default-https-client", # This feature flag enables aws-lc-rs crypto provider
    "rt-tokio",
] } # Needed for Route53
aws-credential-types = { version = "1.2.3", optional = true, features = [
    "hardcoded-credentials",
] } # Needed for Route53
aws-sdk-route53 = { version = "1.84.0", optional = true, default-features = false, features = [
    "default-https-client", # This feature flag enables aws-lc-rs crypto provider
    "rt-tokio",
] }
tokio = { version = "1.47.0", default-features = false, features = [
    "rt",
    "sync",
] }
async-trait = "0.1.88"
anyhow = "1.0.98"
base64 = { version = "0.22.1", optional = true }
hyper = { version = "1.9.0", optional = true }

[features]
default = ["alidns", "arvancloud", "autodns", "azuredns", "baiducloud", "bluecatv2", "bunny", "cloudflare", "cloudns", "constellix", "cpanel", "ddnss", "desec", "digitalocean", "dnsimple", "dnsmadeeasy", "domeneshop", "dreamhost", "duckdns", "dynu", "easydns", "edgedns", "exoscale", "freemyip", "gandiv5", "gcore", "glesys", "godaddy", "googlecloud", "hetzner", "hostingde", "hostinger", "huaweicloud", "hurricane", "ibmcloud", "infoblox", "infomaniak", "inwx", "ionos", "ipv64", "joker", "lightsail", "linode", "luadns", "mythicbeasts", "namecheap", "namedotcom", "namesilo", "netcup", "netlify", "nifcloud", "ns1", "oraclecloud", "ovh", "plesk", "porkbun", "rfc2136", "route53", "safedns", "scaleway", "simplycom", "spaceship", "tencentcloud", "transip", "ultradns", "vercel", "volcengine", "vultr", "websupport", "yandexcloud"]
alidns = ["dns-update"]
arvancloud = ["dns-update"]
autodns = ["dns-update"]
azuredns = ["dns-update"]
baiducloud = ["dns-update"]
bluecatv2 = ["dns-update"]
bunny = ["dns-update"]
cloudflare = ["dns-update"]
cloudns = ["dns-update"]
constellix = ["dns-update"]
cpanel = ["dns-update"]
ddnss = ["dns-update"]
desec = ["dns-update"]
digitalocean = ["dns-update"]
dnsimple = ["dns-update"]
dnsmadeeasy = ["dns-update"]
domeneshop = ["dns-update"]
dreamhost = ["dns-update"]
duckdns = ["dns-update"]
dynu = ["dns-update"]
easydns = ["dns-update"]
edgedns = ["dns-update"]
exoscale = ["dns-update"]
freemyip = ["dns-update"]
gandiv5 = ["dns-update"]
gcore = ["dns-update"]
glesys = ["dns-update"]
godaddy = ["dns-update"]
googlecloud = ["dns-update"]
hetzner = ["dns-update"]
hostingde = ["dns-update"]
hostinger = ["dns-update"]
huaweicloud = ["dns-update"]
hurricane = ["dns-update"]
ibmcloud = ["dns-update"]
infoblox = ["dns-update"]
infomaniak = ["dns-update"]
inwx = ["dns-update"]
ionos = ["dns-update"]
ipv64 = ["dns-update"]
joker = ["dns-update"]
lightsail = ["dns-update"]
linode = ["dns-update"]
luadns = ["dns-update"]
mythicbeasts = ["dns-update"]
namecheap = ["dns-update"]
namedotcom = ["dns-update"]
namesilo = ["dns-update"]
netcup = ["dns-update"]
netlify = ["dns-update"]
nifcloud = ["dns-update"]
ns1 = ["dns-update"]
oraclecloud = ["dns-update"]
ovh = ["dns-update"]
plesk = ["dns-update"]
porkbun = ["dns-update"]
rfc2136 = ["dns-update", "base64", "hyper"]
route53 = ["aws-config", "aws-credential-types", "aws-sdk-route53"]
safedns = ["dns-update"]
scaleway = ["dns-update"]
simplycom = ["dns-update"]
spaceship = ["dns-update"]
tencentcloud = ["dns-update"]
transip = ["dns-update"]
ultradns = ["dns-update"]
vercel = ["dns-update"]
volcengine = ["dns-update"]
vultr = ["dns-update"]
websupport = ["dns-update"]
yandexcloud = ["dns-update"]
