[package]
name = "ferron-http-fauth"
version = "3.0.0-rc.1"
edition = "2021"

[dependencies]
async-trait = "0.1"
ferron-core = { path = "../../core" }
ferron-http = { path = "../../types/http" }
ferron-observability = { path = "../../types/observability" }
http = "1"
http-body-util = "0.1"
bytes = "1"
connpool = "0.2.0"
parking_lot = "0.12.5"
hyper = { version = "1", features = ["client", "http1", "http2"] }
zincio = { version = "0.2.22", default-features = false, features = ["time"] }
zincio-hyper = { version = "0.2.22" }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }
tokio-rustls = { version = "0.26", default-features = false }
webpki-roots = "1.0"
anyhow = "1.0.102"
tokio = "1.52.1"
