[package]
name = "ferron-http-proxy-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ferron-http-proxy = { path = "..", features = ["fuzz"] }
dashmap = "6.2.1"
rustc-hash = "2"

[[bin]]
name = "consistent_hash_ring"
path = "fuzz_targets/consistent_hash_ring.rs"
test = false
required-features = []

[[bin]]
name = "weighted_round_robin"
path = "fuzz_targets/weighted_round_robin.rs"
test = false
required-features = []

[[bin]]
name = "p2c_ewma"
path = "fuzz_targets/p2c_ewma.rs"
test = false
required-features = []

[[bin]]
name = "selector"
path = "fuzz_targets/selector.rs"
test = false
required-features = []
