services:
  ferron:
    build:
      context: ../..
      dockerfile: Dockerfile.alpine
    image: e2e-soak-ferron
    container_name: ferron
    ports:
      - "8080:80"
      - "8889:8889"
    volumes:
      - ./.ferron-test.conf:/etc/ferron/ferron.conf:ro
    depends_on:
      - otel-collector
    networks:
      - ferron-soak
    restart: "no"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GOGC=80
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
      - ferron-soak

  loadgen:
    image: ricoli/hey
    entrypoint: ["hey"]
    networks:
      - ferron-soak

networks:
  ferron-soak:
    driver: bridge
