[package]
name = "ferron-http-server-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ferron-http-server = { path = "..", features = ["fuzz"] }

[[bin]]
name = "canonicalize_path"
path = "fuzz_targets/canonicalize_path.rs"
test = false
required-features = []

[[bin]]
name = "canonicalize_path_routing"
path = "fuzz_targets/canonicalize_path_routing.rs"
test = false
required-features = []
