use clap::Parser;
use std::io::Write;
use std::process::Command;
use tempfile::Builder;

#[derive(Parser, Debug, Clone)]
#[command(
    name = "ferron-serve",
    about = "Utility command to start up a basic HTTP server"
)]
pub struct Cli {
    /// The listening IP to use
    #[arg(short = 'l', long, default_value = "127.0.0.1")]
    pub listen_ip: String,

    /// The port to use
    #[arg(short = 'p', long, default_value_t = 3000)]
    pub port: u16,

    /// The root directory to serve
    #[arg(short = 'r', long, default_value = ".")]
    pub root: String,

    /// Basic authentication credentials for authorized users.
    /// The credential value must be in the form "${user}:${hashed_password}"
    #[arg(short = 'c', long)]
    pub credential: Vec<String>,

    /// Whether to disable brute-force password protection
    #[arg(long)]
    pub disable_brute_protection: bool,

    /// Whether to start the server as a forward proxy
    #[arg(long)]
    pub forward_proxy: bool,

    /// Whether to disable console logs
    #[arg(long)]
    pub disable_console_log: bool,

    /// Whether to enable directory listings
    #[arg(short = 'd', long)]
    pub directory_listing: bool,

    /// Index filenames to try when a request path resolves to a directory
    #[arg(
        short = 'i',
        long,
        num_args(1..),
        default_values = &["index.html", "index.htm", "index.xhtml"]
    )]
    pub index: Vec<String>,

    /// Whether to enable on-the-fly response body compression
    #[arg(long, default_value_t = true, action = clap::ArgAction::Set)]
    pub compress: bool,
}

pub fn generate_config(cli: &Cli) -> String {
    // We could use `ferronconf` crate, but for simplicity,
    // we're using a custom config generation instead...
    let mut config = String::new();
    config.push_str("# Generated by ferron-serve\n");
    config.push_str("{\n");
    config.push_str("  tcp {\n");
    config.push_str(&format!(
        "    listen \"{}\"\n",
        cli.listen_ip
            .as_str()
            .replace('\\', "\\\\")
            .replace('\"', "\\\"")
    ));
    config.push_str("  }\n\n");
    config.push_str("}\n\n");

    config.push_str(&format!("*:{} {{\n", cli.port));
    config.push_str(&format!(
        "  root \"{}\"\n",
        cli.root.replace('\\', "\\\\").replace('\"', "\\\"")
    ));

    if cli.forward_proxy {
        config.push_str("  forward_proxy {\n");
        config.push_str("    allow_domains \"*\"\n");
        config.push_str("    allow_ports 80 443\n");
        config.push_str("  }\n");
    }

    if !cli.credential.is_empty() {
        config.push_str("  basic_auth {\n");
        config.push_str("    realm \"Restricted Access\"\n");
        config.push_str("    users {\n");
        for cred in &cli.credential {
            if let Some((user, hash)) = cred.split_once(':') {
                config.push_str(&format!(
                    "      {} \"{}\"\n",
                    user,
                    hash.replace('\\', "\\\\").replace('\"', "\\\"")
                ));
            }
        }
        config.push_str("    }\n");
        if cli.disable_brute_protection {
            config.push_str("    brute_force_protection {\n");
            config.push_str("      enabled false\n");
            config.push_str("    }\n");
        }
        config.push_str("  }\n");
    }

    if cli.directory_listing {
        config.push_str("  directory_listing\n");
    }

    if !cli.index.is_empty() {
        config.push_str("  index");
        for idx in &cli.index {
            config.push_str(&format!(" \"{}\"", idx.replace('\"', "\\\"")));
        }
        config.push('\n');
    }

    if !cli.compress {
        config.push_str("  compressed false\n");
    }

    // Observability
    if !cli.disable_console_log {
        config.push_str("  console_log\n");
    }

    config.push_str("}\n");
    config
}

fn main() {
    let cli = Cli::parse();
    let config = generate_config(&cli);

    let mut tmpfile = Builder::new()
        .prefix("ferron-serve-")
        .suffix(".conf")
        .tempfile()
        .expect("Failed to create temporary file");

    tmpfile
        .write_all(config.as_bytes())
        .expect("Failed to write to temporary file");
    let tmp_path = tmpfile.path().to_owned();

    // Execute ferron
    let mut ferron_cmd = std::env::current_exe().expect("Failed to get current executable path");
    ferron_cmd.pop();
    ferron_cmd.push("ferron");
    #[cfg(windows)]
    ferron_cmd.set_extension("exe");

    let ferron_path = if ferron_cmd.exists() {
        ferron_cmd
    } else {
        "ferron".into()
    };

    let mut child = Command::new(ferron_path)
        .arg("run")
        .arg("-c")
        .arg(tmp_path)
        .spawn()
        .expect("Failed to execute ferron");

    let status = child.wait().expect("Failed to wait for ferron");

    std::process::exit(status.code().unwrap_or(1));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_config_basic() {
        let cli = Cli {
            listen_ip: "127.0.0.1".to_string(),
            port: 3000,
            root: ".".to_string(),
            credential: vec![],
            disable_brute_protection: false,
            forward_proxy: false,
            disable_console_log: false,
            directory_listing: false,
            index: vec!["index.html".to_string()],
            compress: true,
        };
        let config = generate_config(&cli);
        assert!(config.contains("listen \"127.0.0.1\""));
        assert!(config.contains("*:3000 {"));
        assert!(config.contains("root \".\""));
        assert!(config.contains("console_log"));
    }

    #[test]
    fn test_generate_config_full() {
        let cli = Cli {
            listen_ip: "0.0.0.0".to_string(),
            port: 8080,
            root: "/var/www".to_string(),
            credential: vec!["user:hash".to_string()],
            disable_brute_protection: true,
            forward_proxy: true,
            disable_console_log: true,
            directory_listing: true,
            index: vec!["main.html".to_string()],
            compress: false,
        };
        let config = generate_config(&cli);
        assert!(config.contains("listen \"0.0.0.0\""));
        assert!(config.contains("*:8080 {"));
        assert!(config.contains("root \"/var/www\""));
        assert!(config.contains("forward_proxy"));
        assert!(config.contains("basic_auth"));
        assert!(config.contains("user \"hash\""));
        assert!(config.contains("brute_force_protection"));
        assert!(config.contains("enabled false"));
        assert!(config.contains("directory_listing"));
        assert!(config.contains("index \"main.html\""));
        assert!(config.contains("compressed false"));
        assert!(!config.contains("console_log"));
    }
}
