[package]
name = "ferron-http-ratelimit-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = "1"
ferron-http-ratelimit = { path = "..", features = ["fuzz"] }

[[bin]]
name = "rate_limit_concurrent"
path = "fuzz_targets/rate_limit_concurrent.rs"
test = false
