[package]
name = "ferron-load-modules"
version = "2.8.1"
edition = "2021"

[dependencies]
ferron-common = { workspace = true }
ferron-modules-builtin = { workspace = true, features = [
    "cache",
    "cgi",
    "dcompress",
    "fauth",
    "fcgi",
    "fproxy",
    "fproxyauth",
    "limit",
    "replace",
    "rproxy",
    "scgi",
    "static",
] }
ferron-dns-builtin = { workspace = true, features = [
    "alidns",
    "arvancloud",
    "autodns",
    "azuredns",
    "baiducloud",
    "bluecatv2",
    "bunny",
    "cloudflare",
    "cloudns",
    "constellix",
    "cpanel",
    "ddnss",
    "desec",
    "digitalocean",
    "dnsimple",
    "dnsmadeeasy",
    "domeneshop",
    "dreamhost",
    "duckdns",
    "dynu",
    "easydns",
    "edgedns",
    "exoscale",
    "freemyip",
    "gandiv5",
    "gcore",
    "glesys",
    "godaddy",
    "googlecloud",
    "hetzner",
    "hostingde",
    "hostinger",
    "huaweicloud",
    "hurricane",
    "ibmcloud",
    "infoblox",
    "infomaniak",
    "inwx",
    "ionos",
    "ipv64",
    "joker",
    "lightsail",
    "linode",
    "luadns",
    "mythicbeasts",
    "namecheap",
    "namedotcom",
    "namesilo",
    "netcup",
    "netlify",
    "nifcloud",
    "ns1",
    "oraclecloud",
    "ovh",
    "plesk",
    "porkbun",
    "rfc2136",
    "route53",
    "safedns",
    "scaleway",
    "simplycom",
    "spaceship",
    "tencentcloud",
    "transip",
    "ultradns",
    "vercel",
    "volcengine",
    "vultr",
    "websupport",
    "yandexcloud",
] }
ferron-observability-builtin = { workspace = true, features = [
    "logfile",
    "otlp",
    "stdlog"
] }
anyhow = "1.0.98"

[target.'cfg(unix)'.dev-dependencies]
shiba = { workspace = true }

[build-dependencies]
yaml-rust2 = "0.11.0"
toml = "1.0.0"

[features]
default = ["runtime-monoio"]
runtime-monoio = [
    "ferron-common/runtime-monoio",
    "ferron-modules-builtin/runtime-monoio",
]
runtime-tokio = [
    "ferron-common/runtime-tokio",
    "ferron-modules-builtin/runtime-tokio",
]
runtime-vibeio = [
    "ferron-common/runtime-vibeio",
    "ferron-modules-builtin/runtime-vibeio",
]

[package.metadata.cargo-shear]
ignored = ["anyhow"]
