export default [
  {
    href: "/docs/v3",
    target: "_self",
    label: "Documentation home",
  },
  {
    href: "/docs/v3/getting-started",
    target: "_self",
    label: "Getting started",
  },
  {
    href: "/docs/v3/troubleshooting",
    target: "_self",
    label: "Troubleshooting",
  },
  {
    label: "Installation",
    category: true,
  },
  {
    label: "Linux",
  },
  {
    href: "/docs/v3/installation/linux/installer",
    target: "_self",
    label: "Installer",
    sub: true,
  },
  {
    href: "/docs/v3/installation/linux/debian-ubuntu",
    target: "_self",
    label: "Debian/Ubuntu",
    sub: true,
  },
  {
    href: "/docs/v3/installation/linux/rhel-fedora",
    target: "_self",
    label: "RHEL/Fedora",
    sub: true,
  },
  {
    href: "/docs/v3/installation/windows",
    target: "_self",
    label: "Windows",
  },
  {
    href: "/docs/v3/installation/docker",
    target: "_self",
    label: "Docker",
  },
  {
    href: "/docs/v3/installation/manual-installation",
    target: "_self",
    label: "Manual installation (archive)",
  },
  {
    label: "Building from source",
  },
  {
    href: "/docs/v3/installation/source/default-modules",
    target: "_self",
    label: "Default modules",
    sub: true,
  },
  {
    href: "/docs/v3/installation/source/custom-modules",
    target: "_self",
    label: "Custom modules",
    sub: true,
  },
  {
    label: "Migration",
    category: true,
  },
  {
    href: "/docs/v3/migration/from-v2",
    target: "_self",
    label: "From Ferron 2",
  },
  {
    label: "Common use cases",
    category: true,
  },
  {
    label: "Static & content",
  },
  {
    href: "/docs/v3/use-cases/content/static-files",
    target: "_self",
    label: "Static file serving",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/content/caching",
    target: "_self",
    label: "HTTP caching",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/content/edge-caching",
    target: "_self",
    label: "Edge caching (CDN)",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/content/cgi",
    target: "_self",
    label: "CGI applications",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/content/php",
    target: "_self",
    label: "PHP hosting",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/content/php-edge-cache",
    target: "_self",
    label: "PHP edge caching (LSCache)",
    sub: true,
  },
  {
    label: "Traffic & routing",
  },
  {
    href: "/docs/v3/use-cases/traffic/reverse-proxy",
    target: "_self",
    label: "Reverse proxying",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/traffic/url-rewriting",
    target: "_self",
    label: "URL rewriting",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/traffic/error-pages",
    target: "_self",
    label: "Error pages",
    sub: true,
  },
  {
    label: "Security",
  },
  {
    href: "/docs/v3/use-cases/security/automatic-tls",
    target: "_self",
    label: "Automatic TLS",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/rate-limiting",
    target: "_self",
    label: "Rate limiting",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/abuse-protection",
    target: "_self",
    label: "Abuse protection",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/security-headers",
    target: "_self",
    label: "Security headers",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/manual-tls",
    target: "_self",
    label: "Manual TLS",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/mtls",
    target: "_self",
    label: "mTLS (mutual TLS)",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/access-control",
    target: "_self",
    label: "Access control",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security/fail2ban",
    target: "_self",
    label: "Fail2ban integration",
    sub: true,
  },
  {
    label: "Operations",
  },
  {
    href: "/docs/v3/use-cases/operations/admin-api",
    target: "_self",
    label: "Admin API",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/operations/logging-observability",
    target: "_self",
    label: "Logging & observability",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/operations/ferron-serve",
    target: "_self",
    label: "'ferron-serve' command",
    sub: true,
  },
  {
    label: "Configuration",
    category: true,
  },
  {
    label: "Fundamentals",
  },
  {
    href: "/docs/v3/configuration/fundamentals/syntax",
    target: "_self",
    sub: true,
    label: "Syntax and file structure",
  },
  {
    href: "/docs/v3/configuration/fundamentals/json-config",
    target: "_self",
    sub: true,
    label: "JSON configuration",
  },
  {
    href: "/docs/v3/configuration/fundamentals/validation",
    target: "_self",
    sub: true,
    label: "Configuration validation",
  },
  {
    href: "/docs/v3/configuration/fundamentals/doctor",
    target: "_self",
    sub: true,
    label: "Configuration doctor",
  },
  {
    href: "/docs/v3/configuration/fundamentals/formatting",
    target: "_self",
    sub: true,
    label: "Configuration formatting",
  },
  {
    href: "/docs/v3/configuration/fundamentals/conditionals",
    target: "_self",
    sub: true,
    label: "Conditionals and variables",
  },
  {
    label: "Server",
  },
  {
    href: "/docs/v3/configuration/server/core-directives",
    target: "_self",
    sub: true,
    label: "Core directives",
  },
  {
    href: "/docs/v3/configuration/server/host",
    target: "_self",
    sub: true,
    label: "HTTP host directives",
  },
  {
    label: "Routing & control",
  },
  {
    href: "/docs/v3/configuration/routing/url-processing",
    target: "_self",
    sub: true,
    label: "Routing and URL processing",
  },
  {
    href: "/docs/v3/configuration/routing/response",
    target: "_self",
    sub: true,
    label: "HTTP response control and early hints",
  },
  {
    href: "/docs/v3/configuration/routing/rewrite",
    target: "_self",
    sub: true,
    label: "URL rewriting",
  },
  {
    href: "/docs/v3/configuration/routing/map",
    target: "_self",
    sub: true,
    label: "HTTP map",
  },
  {
    href: "/docs/v3/configuration/routing/variables",
    target: "_self",
    sub: true,
    label: "Variable setting",
  },
  {
    label: "Proxying",
  },
  {
    href: "/docs/v3/configuration/proxy/reverse-proxy",
    target: "_self",
    sub: true,
    label: "Reverse proxy",
  },
  {
    href: "/docs/v3/configuration/proxy/forward-proxy",
    target: "_self",
    sub: true,
    label: "Forward proxy",
  },
  {
    label: "Security",
  },
  {
    href: "/docs/v3/configuration/security/basic-auth",
    target: "_self",
    sub: true,
    label: "HTTP basic authentication",
  },
  {
    href: "/docs/v3/configuration/security/forwarded-auth",
    target: "_self",
    sub: true,
    label: "Forwarded authentication",
  },
  {
    href: "/docs/v3/configuration/security/tls",
    target: "_self",
    sub: true,
    label: "Security and TLS",
  },
  {
    href: "/docs/v3/configuration/security/acme",
    target: "_self",
    sub: true,
    label: "ACME automatic TLS",
  },
  {
    href: "/docs/v3/configuration/security/dns-providers",
    target: "_self",
    sub: true,
    label: "DNS providers",
  },
  {
    href: "/docs/v3/configuration/security/local-tls",
    target: "_self",
    sub: true,
    label: "Local development TLS",
  },
  {
    href: "/docs/v3/configuration/security/tls-http",
    target: "_self",
    sub: true,
    label: "HTTP TLS provider",
  },
  {
    href: "/docs/v3/configuration/security/session-tickets",
    target: "_self",
    sub: true,
    label: "TLS session ticket keys",
  },
  {
    href: "/docs/v3/configuration/security/ocsp",
    target: "_self",
    sub: true,
    label: "OCSP stapling",
  },
  {
    label: "Content & traffic",
  },
  {
    href: "/docs/v3/configuration/content/static-files",
    target: "_self",
    sub: true,
    label: "Static file serving",
  },
  {
    href: "/docs/v3/configuration/content/compression",
    target: "_self",
    sub: true,
    label: "HTTP compression",
  },
  {
    href: "/docs/v3/configuration/content/cache",
    target: "_self",
    sub: true,
    label: "HTTP cache",
  },
  {
    href: "/docs/v3/configuration/content/cgi",
    target: "_self",
    sub: true,
    label: "CGI support",
  },
  {
    href: "/docs/v3/configuration/content/fastcgi",
    target: "_self",
    sub: true,
    label: "FastCGI support",
  },
  {
    href: "/docs/v3/configuration/content/scgi",
    target: "_self",
    sub: true,
    label: "SCGI support",
  },
  {
    href: "/docs/v3/configuration/content/buffering",
    target: "_self",
    sub: true,
    label: "HTTP buffering",
  },
  {
    href: "/docs/v3/configuration/content/response-replace",
    target: "_self",
    sub: true,
    label: "HTTP response body replacement",
  },
  {
    href: "/docs/v3/configuration/content/headers",
    target: "_self",
    sub: true,
    label: "HTTP headers and CORS",
  },
  {
    href: "/docs/v3/configuration/content/rate-limit",
    target: "_self",
    sub: true,
    label: "Rate limiting",
  },
  {
    href: "/docs/v3/configuration/content/abuse-ban",
    target: "_self",
    sub: true,
    label: "Abuse protection",
  },
  {
    label: "Observability",
  },
  {
    href: "/docs/v3/configuration/observability/logging",
    target: "_self",
    label: "Logging",
    sub: true,
  },
  {
    href: "/docs/v3/configuration/observability/metrics",
    target: "_self",
    label: "Metrics",
    sub: true,
  },
  {
    href: "/docs/v3/configuration/observability/tracing",
    target: "_self",
    label: "Tracing",
    sub: true,
  },
  {
    href: "/docs/v3/configuration/observability/otlp",
    target: "_self",
    label: "OTLP observability",
    sub: true,
  },
  {
    href: "/docs/v3/configuration/observability/prometheus",
    target: "_self",
    label: "Prometheus metrics",
    sub: true,
  },
  {
    href: "/docs/v3/configuration/observability/control-plane",
    target: "_self",
    label: "Cross-plane traceability",
    sub: true,
  },
];
