export default [
  {
    href: "/docs/v3",
    target: "_self",
    sub: false,
    label: "Welcome to the documentation!",
  },
  {
    href: "/docs/v3/status-and-limitations",
    target: "_self",
    label: "Status and limitations",
  },
  {
    label: "Installation",
    category: true,
  },
  {
    href: "/docs/v3/installation/building-from-source",
    target: "_self",
    label: "Building from source",
  },
  {
    label: "Common use cases",
    category: true,
  },
  {
    label: "Static & content",
  },
  {
    href: "/docs/v3/use-cases/static-file-serving",
    target: "_self",
    label: "Static file serving",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/http-caching",
    target: "_self",
    label: "HTTP caching",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/http-cgi",
    target: "_self",
    label: "CGI applications",
    sub: true,
  },
  {
    label: "Traffic & routing",
  },
  {
    href: "/docs/v3/use-cases/reverse-proxy",
    target: "_self",
    label: "Reverse proxying",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/url-rewriting",
    target: "_self",
    label: "URL rewriting",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/error-pages",
    target: "_self",
    label: "Error pages",
    sub: true,
  },
  {
    label: "Security",
  },
  {
    href: "/docs/v3/use-cases/automatic-tls",
    target: "_self",
    label: "Automatic TLS",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/rate-limiting",
    target: "_self",
    label: "Rate limiting",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/security-headers",
    target: "_self",
    label: "Security headers",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/manual-tls",
    target: "_self",
    label: "Manual TLS",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/mtls",
    target: "_self",
    label: "mTLS (mutual TLS)",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/access-control",
    target: "_self",
    label: "Access control",
    sub: true,
  },
  {
    href: "/docs/v3/use-cases/logging-observability",
    target: "_self",
    label: "Logging & observability",
  },
  {
    label: "Configuration",
    category: true,
  },
  {
    label: "Fundamentals",
  },
  {
    href: "/docs/v3/configuration/syntax",
    target: "_self",
    sub: true,
    label: "Syntax and file structure",
  },
  {
    href: "/docs/v3/configuration/json-config",
    target: "_self",
    sub: true,
    label: "JSON configuration",
  },
  {
    href: "/docs/v3/configuration/conditionals",
    target: "_self",
    label: "Conditionals and variables",
  },
  {
    label: "Server",
  },
  {
    href: "/docs/v3/configuration/core-directives",
    target: "_self",
    sub: true,
    label: "Core directives",
  },
  {
    href: "/docs/v3/configuration/http-host",
    target: "_self",
    sub: true,
    label: "HTTP host directives",
  },
  {
    label: "Routing & control",
  },
  {
    href: "/docs/v3/configuration/routing-url-processing",
    target: "_self",
    sub: true,
    label: "Routing and URL processing",
  },
  {
    href: "/docs/v3/configuration/http-response",
    target: "_self",
    sub: true,
    label: "HTTP response control and early hints",
  },
  {
    href: "/docs/v3/configuration/http-rewrite",
    target: "_self",
    sub: true,
    label: "URL rewriting",
  },
  {
    href: "/docs/v3/configuration/http-map",
    target: "_self",
    sub: true,
    label: "HTTP map",
  },
  {
    label: "Proxying",
  },
  {
    href: "/docs/v3/configuration/reverse-proxying",
    target: "_self",
    sub: true,
    label: "Reverse proxy",
  },
  {
    href: "/docs/v3/configuration/http-fproxy",
    target: "_self",
    sub: true,
    label: "Forward proxy",
  },
  {
    label: "Security",
  },
  {
    href: "/docs/v3/configuration/http-basicauth",
    target: "_self",
    sub: true,
    label: "HTTP basic authentication",
  },
  {
    href: "/docs/v3/configuration/http-fauth",
    target: "_self",
    sub: true,
    label: "Forwarded authentication",
  },
  {
    href: "/docs/v3/configuration/security-tls",
    target: "_self",
    sub: true,
    label: "Security and TLS",
  },
  {
    href: "/docs/v3/configuration/tls-acme",
    target: "_self",
    sub: true,
    label: "ACME automatic TLS",
  },
  {
    href: "/docs/v3/configuration/dns-providers",
    target: "_self",
    sub: true,
    label: "DNS providers",
  },
  {
    href: "/docs/v3/configuration/tls-local",
    target: "_self",
    sub: true,
    label: "Local development TLS",
  },
  {
    href: "/docs/v3/configuration/tls-session-tickets",
    target: "_self",
    sub: true,
    label: "TLS session ticket keys",
  },
  {
    href: "/docs/v3/configuration/ocsp-stapling",
    target: "_self",
    sub: true,
    label: "OCSP stapling",
  },
  {
    label: "Content & traffic",
  },
  {
    href: "/docs/v3/configuration/static-content",
    target: "_self",
    sub: true,
    label: "Static file serving",
  },
  {
    href: "/docs/v3/configuration/http-cache",
    target: "_self",
    sub: true,
    label: "HTTP cache",
  },
  {
    href: "/docs/v3/configuration/http-cgi",
    target: "_self",
    sub: true,
    label: "CGI support",
  },
  {
    href: "/docs/v3/configuration/http-scgi",
    target: "_self",
    sub: true,
    label: "SCGI support",
  },
  {
    href: "/docs/v3/configuration/http-buffer",
    target: "_self",
    sub: true,
    label: "HTTP buffering",
  },
  {
    href: "/docs/v3/configuration/http-replace",
    target: "_self",
    sub: true,
    label: "HTTP response body replacement",
  },
  {
    href: "/docs/v3/configuration/http-headers",
    target: "_self",
    sub: true,
    label: "HTTP headers and CORS",
  },
  {
    href: "/docs/v3/configuration/http-ratelimit",
    target: "_self",
    sub: true,
    label: "Rate limiting",
  },
  {
    label: "Observability",
  },
  {
    href: "/docs/v3/configuration/observability-logging",
    target: "_self",
    sub: true,
    label: "Observability & logging",
  },
  {
    href: "/docs/v3/configuration/observability-otlp",
    target: "_self",
    sub: true,
    label: "OTLP observability",
  },
  {
    href: "/docs/v3/configuration/observability-prometheus",
    target: "_self",
    sub: true,
    label: "Prometheus metrics",
  },
  {
    href: "/docs/v3/configuration/http-trace",
    target: "_self",
    sub: true,
    label: "Trace context",
  },
];
