export default [
  {
    href: "/docs",
    target: "_self",
    sub: false,
    label: "Welcome to the documentation!",
  },
  {
    href: "/docs/playground",
    target: "_self",
    sub: false,
    label: "Playground",
  },
  {
    label: "Installation",
  },
  {
    href: "/docs/installation/installer-linux",
    target: "_self",
    sub: true,
    label: "Installer (GNU/Linux)",
  },
  {
    href: "/docs/installation/installer-windows",
    target: "_self",
    sub: true,
    label: "Installer (Windows Server)",
  },
  {
    href: "/docs/installation/debian",
    target: "_self",
    sub: true,
    label: "Debian/Ubuntu",
  },
  {
    href: "/docs/installation/rpm",
    target: "_self",
    sub: true,
    label: "RHEL/Fedora",
  },
  {
    href: "/docs/installation/docker",
    target: "_self",
    sub: true,
    label: "Docker",
  },
  {
    href: "/docs/installation/package-managers",
    target: "_self",
    sub: true,
    label: "Package managers (community)",
  },
  {
    href: "/docs/installation/manual",
    target: "_self",
    sub: true,
    label: "Manual installation",
  },
  {
    label: "Common use cases",
  },
  {
    href: "/docs/use-cases/static-file-serving",
    target: "_self",
    sub: true,
    label: "Static file serving",
  },
  {
    href: "/docs/use-cases/reverse-proxy",
    target: "_self",
    sub: true,
    label: "Reverse proxying",
  },
  {
    href: "/docs/use-cases/php",
    target: "_self",
    sub: true,
    label: "PHP hosting",
  },
  {
    href: "/docs/use-cases/cgi-applications",
    target: "_self",
    sub: true,
    label: "CGI applications",
  },
  {
    href: "/docs/use-cases/web-applications",
    target: "_self",
    sub: true,
    label: "Web applications",
  },
  {
    href: "/docs/use-cases/redirecting",
    target: "_self",
    sub: true,
    label: "Redirecting",
  },
  {
    href: "/docs/use-cases/automatic-tls",
    target: "_self",
    sub: true,
    label: "Automatic TLS",
  },
  {
    href: "/docs/use-cases/ferron-serve",
    target: "_self",
    sub: true,
    label: "`ferron serve` subcommand",
  },
  {
    href: "/docs/use-cases/logging-observability",
    target: "_self",
    sub: true,
    label: "Logging and observability",
  },
  {
    label: "Configuration",
  },
  {
    href: "/docs/configuration/fundamentals",
    target: "_self",
    sub: true,
    label: "Fundamentals",
  },
  {
    href: "/docs/configuration/core-directives",
    target: "_self",
    sub: true,
    label: "Core directives",
  },
  {
    href: "/docs/configuration/security-tls",
    target: "_self",
    sub: true,
    label: "Security & TLS",
  },
  {
    href: "/docs/configuration/reverse-proxying",
    target: "_self",
    sub: true,
    label: "Reverse proxying",
  },
  {
    href: "/docs/configuration/static-content",
    target: "_self",
    sub: true,
    label: "Static & content handling",
  },
  {
    href: "/docs/configuration/routing-url-processing",
    target: "_self",
    sub: true,
    label: "Routing & URL processing",
  },
  {
    href: "/docs/configuration/application-backends",
    target: "_self",
    sub: true,
    label: "Application backends",
  },
  {
    href: "/docs/configuration/traffic-control",
    target: "_self",
    sub: true,
    label: "Traffic control",
  },
  {
    href: "/docs/configuration/observability-logging",
    target: "_self",
    sub: true,
    label: "Observability & logging",
  },
  {
    href: "/docs/configuration/placeholders",
    target: "_self",
    sub: true,
    label: "Placeholders",
  },
  {
    href: "/docs/configuration/subconditions",
    target: "_self",
    sub: true,
    label: "Subconditions",
  },
  {
    href: "/docs/configuration/examples",
    target: "_self",
    sub: true,
    label: "Configuration examples",
  },
  {
    label: "Reference",
  },
  {
    href: "/docs/reference/configuration-legacy",
    target: "_self",
    sub: true,
    label: "Server configuration (legacy)",
  },
  {
    href: "/docs/reference/modules",
    target: "_self",
    sub: true,
    label: "Server modules",
  },
  {
    href: "/docs/reference/observability",
    target: "_self",
    sub: true,
    label: "Observability backends",
  },
  {
    href: "/docs/reference/commands",
    target: "_self",
    sub: true,
    label: "Commands",
  },
  {
    href: "/docs/reference/ferrbench",
    target: "_self",
    sub: true,
    label: "FerrBench",
  },
  {
    href: "https://rustdocs-v2.ferron.sh",
    target: "_self",
    sub: true,
    label: "Rust crate documentation",
  },
];
