[package]
name = "ferron-http-static"
version = "3.0.0-beta.2"
edition = "2021"

[dependencies]
async-trait = "0.1"
vibeio = { version = "0.2.6", default-features = false, features = ["fs"] }
vibeio-http = { version = "0.3.0", default-features = false, features = ["h1", "h2", "h1-zerocopy"] }
ferron-core = { path = "../../core" }
ferron-http = { path = "../../types/http", features = ["util"] }
ferron-observability = { path = "../../types/observability" }
http = "1"
http-body = "1"
http-body-util = "0.1"
bytes = "1"
tokio-util = { version = "0.7", features = ["io", "rt"] }
futures-util = "0.3"
futures-core = "0.3"
send_wrapper = { version = "0.6", features = ["futures"] }
async-compression = { version = "0.4", features = ["tokio", "gzip", "brotli", "deflate", "zstd"] }
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
multi-mime-guess = "0.1"
urlencoding = "2"
chrono = "0.4"
phf = { version = "0.14", features = ["macros"] }
rand = "0.10.1"
hex = "0.4.3"
pin-project-lite = "0.2.17"
httpdate = "1.0.3"

[package.metadata.cargo-shear]
ignored = ["flate2"]
