name: Deploy website ("develop" branch)

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'blog/**'
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/deploy-website-develop.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ferron-website-develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Install dependencies
        shell: bash
        run: |
          pushd website
          npm ci || npm install
          popd

      - name: Build the website
        shell: bash
        run: |
          pushd website
          npm run build
          echo "User-agent: *" > dist/robots.txt
          echo "Disallow: /" >> dist/robots.txt
          popd

      - name: Create the website ZIP archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "../../ferron-website-develop.zip"
          directory: "website/dist"
      
      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.5
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: ferron-servers
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}

      - name: Deploy the website
        shell: bash
        run: |
          scp ferron-website-develop.zip ferron-servers:.

          # The "deploy-ferron-website-develop" is a custom command that deploys the Ferron website
          ssh ferron-servers "sudo deploy-ferron-website-develop ferron-website-develop.zip && rm ferron-website-develop.zip"