name: Deploy website (staging)

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'blog/**'
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/deploy-website-staging.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ferron-website-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        shell: bash
        run: |
          pushd website
          npm ci || npm install
          popd

      - name: Build the website
        shell: bash
        run: |
          pushd website
          npm run build
          popd

      - name: Create the website ZIP archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "../../ferron-website-staging.zip"
          directory: "website/dist"
      
      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.5
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: ferron-servers
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}

      - name: Deploy the website
        shell: bash
        run: |
          scp ferron-website-staging.zip ferron-servers:.

          # The "deploy-ferron-website-staging" is a custom command that deploys the Ferron website
          ssh ferron-servers "sudo deploy-ferron-website-staging ferron-website-staging.zip && rm ferron-website-staging.zip"