name: Deploy website (Ferron 2.x)

on:
  push:
    branches: ["2.x"]
    paths:
      - "blog/**"
      - "docs/**"
      - "website/**"
      - ".github/workflows/deploy-website-v2.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: warp-ubuntu-latest-x64-8x
    environment: ferron-website-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: 2.x

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        shell: bash
        run: |
          pushd website
          bun ci || bun install
          popd

      - name: Build the website
        shell: bash
        run: |
          pushd website
          bun run --bun build
          popd

      - name: Precompress the website
        shell: bash
        run: |
          docker run --rm -u "$(id -u):$(id -g)" -v ./website/dist:/tmp/website ferronserver/ferron:2 ferron-precompress /tmp/website

      - name: Create the website ZIP archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "../../ferron2-website.zip"
          directory: "website/dist"

      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: ferron-servers
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}

      - name: Deploy the website
        shell: bash
        run: |
          scp ferron2-website.zip ferron-servers:.

          # The "deploy-ferron2-website" is a custom command that deploys the Ferron website
          ssh ferron-servers "sudo deploy-ferron2-website ferron2-website.zip && rm ferron2-website.zip"
