name: Run E2E tests (Ferron 2.x)

on:
  push:
    branches: ["develop-2.x"]
    paths:
      - ".dockerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - "e2e/**"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "wwwroot/**"
      - ".github/workflows/e2e-v2.yml"
  pull_request:
    branches: ["develop-2.x"]
    paths:
      - ".dockerignore"
      - "Cargo.lock"
      - "Cargo.toml"
      - "e2e/**"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "wwwroot/**"
      - ".github/workflows/e2e-v2.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            e2e -> target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set up protoc
        uses: arduino/setup-protoc@v3

      # Build the test Ferron image to cache it for the test suite
      - name: Build the test Ferron image
        uses: docker/build-push-action@v7.1.0
        with:
          context: .
          file: e2e/Dockerfile.test
          load: true
          tags: e2e-test-ferron:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run the test suite
        shell: bash
        run: |
          cd e2e
          cargo test
