name: Release (CI test)

on:
  push:
    branches: [ "develop" ]

jobs:
  release:
    # Set the job to run on the platform specified by the matrix below
    runs-on: ${{ matrix.runner }}
 
    permissions:
      contents: write

    # Define the build matrix for cross-compilation
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            command: cross
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            command: cross
          - target: i686-unknown-linux-gnu
            runner: ubuntu-latest
            command: cross
          - target: i686-unknown-linux-musl
            runner: ubuntu-latest
            command: cross
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
            command: cross
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-latest
            command: cross
          - target: armv7-unknown-linux-gnueabihf
            runner: ubuntu-latest
            command: cross
          - target: armv7-unknown-linux-musleabihf
            runner: ubuntu-latest
            command: cross
          - target: riscv64gc-unknown-linux-gnu
            runner: ubuntu-latest
            command: cross
          - target: s390x-unknown-linux-gnu
            runner: ubuntu-latest
            command: cross
          - target: x86_64-unknown-freebsd
            runner: ubuntu-latest
            command: cross
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            command: cargo
          - target: i686-pc-windows-msvc
            runner: windows-latest
            command: cargo
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
            command: cargo
          - target: x86_64-apple-darwin
            runner: macos-latest
            command: cargo
          - target: aarch64-apple-darwin
            runner: macos-latest
            command: cargo
 
    # The steps to run for each matrix item
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
 
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"
 
      - name: Setup cache
        if: matrix.command != 'cross'
        uses: Swatinem/rust-cache@v2

      - name: Determine Ferron version
        shell: bash
        run: |
          FERRON_VERSION_CARGO="$(cat ferron/Cargo.toml | grep -E '^version' | sed -E 's|.*"([0-9a-zA-Z.+-]+)"$|\1|g')"
          FERRON_VERSION_GIT="$(git tag --sort=-committerdate | head -n 1 | sed s/[^0-9a-zA-Z.+-]//g)"
          if [ "$FERRON_VERSION_CARGO" != "" ]; then
            echo "Version determined from Cargo.toml file"
            echo "FERRON_VERSION=$FERRON_VERSION_CARGO" >> $GITHUB_ENV
          elif  [ "$FERRON_VERSION_GIT" != "" ]; then
            echo "Version determined from the Git tag"
            echo "FERRON_VERSION=$FERRON_VERSION_GIT" >> $GITHUB_ENV
          else
            echo "Can't determine the server version!" 2>&1
            exit 1
          fi

      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross --force

      - name: Build binaries
        run: "${{ matrix.command }} build --verbose --locked --release --target ${{ matrix.target }}"

      - name: Prepare for packaging
        shell: bash
        run: |
          mkdir release
          find target/${{ matrix.target }}/release -mindepth 1 -maxdepth 1 -type f ! -name "*.*" -o -name "*.exe" -o -name "*.dll" -o -name "*.dylib" -o -name "*.so" | sed -E "s|(.*)|cp -a \1 release|" | bash
          cp -a ferron-release.yaml release/ferron.yaml
          cp -a wwwroot release

      - name: Create a release ZIP archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "../ferron-${{ env.FERRON_VERSION }}-${{ matrix.target }}.zip"
          directory: "release"

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "ferron-${{ env.FERRON_VERSION }}-${{ matrix.target }}.zip"
          tag: "${{ env.FERRON_VERSION }}"
          draft: true