name: Rust (Ferron 2.x)

on:
  push:
    branches: ["develop-2.x"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-passwd/**"
      - "ferron-yaml2kdl/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "smoketest/**"
      - ".github/workflows/rust-v2.yml"
  pull_request:
    branches: ["develop-2.x"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-passwd/**"
      - "ferron-yaml2kdl/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - ".github/workflows/rust-v2.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo tests
        run: cargo test --workspace --verbose

      - name: Build binaries
        shell: bash
        run: |
          cargo run --manifest-path build-prepare/Cargo.toml
          cd build-workspace
          while [ "$OLD_CONFLICTING_PACKAGES" != "$CONFLICTING_PACKAGES" ] || [ "$OLD_CONFLICTING_PACKAGES" = "" ]; do \
              OLD_CONFLICTING_PACKAGES=$CONFLICTING_PACKAGES; \
              CONFLICTING_PACKAGES=$( (cargo update -w --dry-run 2>&1 || true) | (grep -E '^error: failed to select a version for (the requirement )?`[^ `]+' || true) | sed -E 's|[^`]*`([^ `]+).*|\1|' | xargs); \
              if [ "$CONFLICTING_PACKAGES" = "" ]; then \
                  break; \
              fi; \
              if [ "$OLD_CONFLICTING_PACKAGES" = "$CONFLICTING_PACKAGES" ]; then \
                  echo "Couldn't resolve Cargo conflicts" >&2; \
                  exit 1; \
              fi; \
              if [ "$CONFLICTING_PACKAGES" != "" ]; then \
                  cargo update $CONFLICTING_PACKAGES || true; \
              fi; \
          done
          ${{ matrix.command }} build --verbose --release --target-dir ../target --target ${{ matrix.target }} ${{ matrix.options }}
          cd ..

      - name: Smoke test the binary
        shell: bash
        run: |
          FERRON="$(pwd)/target/${{ matrix.target }}/release/ferron" bash smoketest/smoketest.sh

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check linting
        run: cargo clippy --workspace -- -D warnings
