name: Rust (Ferron 2.x)

on:
  push:
    branches: ["develop-2.x"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-passwd/**"
      - "ferron-yaml2kdl/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - "smoketest/**"
      - ".github/workflows/develop-test-v2.yml"
  pull_request:
    branches: ["develop-2.x"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "ferron/**"
      - "ferron-common/**"
      - "ferron-dns-builtin/**"
      - "ferron-load-modules/**"
      - "ferron-modules-builtin/**"
      - "ferron-passwd/**"
      - "ferron-yaml2kdl/**"
      - "ferron-yaml2kdl-core/**"
      - "ferron-build.yaml"
      - "ferron-build-override.yaml"
      - ".github/workflows/rust-v2.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo tests
        run: cargo test --workspace --verbose

      - name: Build binaries
        shell: bash
        run: |
          CARGO_FINAL_EXTRA_ARGS="--verbose" make build

      - name: Smoke test the binary
        shell: bash
        run: |
          FERRON="$(pwd)/target/${{ matrix.target }}/release/ferron" bash smoketest/smoketest.sh

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check linting
        run: cargo clippy --workspace -- -D warnings
