name: Rust crate docs (temporary)

on:
  push:
    branches: ["develop"]
    paths:
      - ".github/workflows/temp-docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Generate the Rust crate documentation
        run: "cargo doc --verbose --locked --release --no-deps"

      - name: Create the documentation ZIP archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "../../ferron-rustdocs.zip"
          directory: "target/doc"

      - name: Set up SSH
        uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          ORIGIN: ${{ secrets.SSH_HOSTNAME }}
          SSHKEY: ${{ secrets.SSH_KEY }}
          NAME: ferron-servers
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USERNAME }}

      - name: Deploy the documentation
        shell: bash
        run: |
          scp ferron-rustdocs.zip ferron-servers:.

          # The "deploy-ferron-rustdocs" is a custom command that deploys the Ferron's Rust crate documentation
          ssh ferron-servers "/usr/bin/sudo-rs deploy-ferron-rustdocs ferron-rustdocs.zip && rm ferron-rustdocs.zip"
