[package]
name = "ferron-tls"
version = "3.0.0-beta.10"
edition = "2021"

[dependencies]
async-trait = "0.1"
aws-lc-rs = { version = "1", features = ["bindgen"] }
rustls = { version = "0.23.37", default-features = false, features = ["std", "tls12", "aws_lc_rs"] }
rustls-pki-types = "1"
rustls-native-certs = "0.8"
webpki-roots = "1"
zincio = { version = "0.2.22", default-features = false }
tokio-rustls = { version = "0.26.4", default-features = false }
rasn = { version = "0.28.13", optional = true }
rasn-pkix = { version = "0.28.13", optional = true }
num-bigint = { version = "0.4", optional = true }
ferron-observability = { path = "../../types/observability", optional = true }
ferron-core = { path = "../../core" }
tokio = { version = "1.53.1", features = ["io-util"] }
rand = "0.10.2"

[features]
default = []
observability = ["dep:rasn", "dep:rasn-pkix", "dep:num-bigint", "dep:ferron-observability"]
fips = ["rustls/fips"]

[dev-dependencies]
tempfile = "3"
